# Generated by Django 5.2.3 on 2025-07-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_specialization_doctorprofile_patientprofile_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorspecialization',
            name='experiece_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
