# Generated by Django 5.2.3 on 2025-07-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medlink', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
